version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: build.dockerfile
    container_name: devskillstest
    volumes:
      - ./SkillsTest:/var/www/html
    networks:
      - laravel
    ports:
      - 80:80
      - 443:443
      - 5173:5173
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sandbox
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
