version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: build.dockerfile
    container_name: LaravelSandbox
    volumes:
      - ./SkillsTest:/var/www/html
    networks:
      - laravel
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.12
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sandbox
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
volumes:
  shared:
