version: '3'

services:
  site:
    build:
      context: .
      dockerfile: build.dockerfile
    container_name: devskillstest
    volumes:
      - ./SkillsTest:/var/www/html
    ports:
      - 80:80
      - 5173:5173
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
