version: '3'

networks:
  laravel:

services:
  site:
    image: 800797377039.dkr.ecr.us-east-2.amazonaws.com/claritycore:test
    container_name: LaravelSandbox
    volumes:
      - ./app:/var/www/html/app
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./tests:/var/www/html/tests
    networks:
      - laravel
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.12
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sandbox
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
volumes:
  shared:
